<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/%23_10_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Massivga yo'naltirilgan dasturlash

Tartiblash (`Sorting`)

In [1]:
import numpy as np

In [3]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan iborat massiv
arr

array([0.62108766, 0.63060896, 0.94077961, 0.39333456])

`sort` funksiyasi

In [7]:
# 1-usul
sorted_arr = np.sort(arr) #arr'ni yangi array'da tartiblangan versiyasi
sorted_arr

array([0.39333456, 0.62108766, 0.63060896, 0.94077961])

In [8]:
# 2-usul
arr.sort()
arr

array([0.39333456, 0.62108766, 0.63060896, 0.94077961])

In [10]:
# teskari tartiblash
rev_arr = -np.sort(-arr) # teskari tartiblangan arr
rev_arr

array([0.94077961, 0.63060896, 0.62108766, 0.39333456])

In [15]:
# 2D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[-1.33724424,  0.52937245, -0.0734303 , -1.54214007],
       [-0.2841463 , -0.49711379, -0.46222778,  0.10955828]])

In [16]:
# axis = 0 -> Qator o'qi
row_srt = np.sort(arr2d, axis = 0)
row_srt

array([[-1.33724424, -0.49711379, -0.46222778, -1.54214007],
       [-0.2841463 ,  0.52937245, -0.0734303 ,  0.10955828]])

In [17]:
# axis = 1 -> Ustun o'qi
col_srt = np.sort(arr2d, axis = 1)
col_srt

array([[-1.54214007, -1.33724424, -0.0734303 ,  0.52937245],
       [-0.49711379, -0.46222778, -0.2841463 ,  0.10955828]])