<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/%23_12_File_saves_loads.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili
*   Fayllar bilan ishlash




In [81]:
import numpy as np

In [82]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
np.save('data', arr) # faylni .npy ko'rinishida saqlash

In [84]:
ints1 = np.load('data.npy') # faylni ochish
ints1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
# data1
ints2 = np.arange(1,21)
ints2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [86]:
np.savez("arrays", a=ints1, b=ints2) # ints1 va ints2 ma'lumotlarini a va b o'zgaruvchiga yuklab arrays.nps fayliga yuklaymiz

In [87]:
arrays = np.load('arrays.npz')


In [88]:
arrays['a']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arrays['b']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
np.savez_compressed('arr_compr.npz', a=ints1, b=ints2) # a va b ma'lumotlarni siqilgan holatda faylga yuklash

In [96]:
arr_compr = np.load('arr_compr.npz') # siqilgan faylni o'zgaruvchiga yuklagan holda ochish

In [98]:
arr_compr['a'] # fayldagi a qiymat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr_compr['b'] # fayldagi b qiymat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])