<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/%23_1_creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Numpyda massiv yaratishning eng oson yo'llaridan biri bu `array` funksiyasi yordamida amalga oshiriladi. Ushbu funksiya har qanday ketma-ket turdagi ma'lumotlarni qabul qilib, uni yangi Numpy `array`ga o'girib beradi.

In [10]:
data1 = [3.5, 8, 4, 7] # list
arr1 = np.array(data1) # array

In [6]:
data1
arr1

array([3.5, 8. , 4. , 7. ])

In [11]:
data2 = (4, 5, 3.6, 9) # tuple
arr2 = np.array(data2) # array

In [8]:
arr2

array([4. , 5. , 3.6, 9. ])

In [9]:
data2

(4, 5, 3.6, 9)

Massivni o'lchash - `.ndim` metodi yordamida amalga oshiriladi

In [12]:
arr1.ndim

1

In [13]:
arr2.ndim

1

ikki va undan katta o'lchamli massivlar

In [14]:
data3 = [[1, 2, 4, 6], [3, 5, 7, 8]]
arr3 = np.array(data3)

In [15]:
arr3

array([[1, 2, 4, 6],
       [3, 5, 7, 8]])

In [81]:
arr3.ndim

2

In [94]:
data_3 = [[[1,5,6,7], [2, 23, 21, 63, 0], [42, 63, 8, 25, 11]], [[62, 25, 88, 14, 21], [123, 634, 234, 773], [53, 36, 72, 15, 7]], [[1, 2, 3, 4, 5], [1, 3, 5, 7, 9], [14, 15, 1, 8, 4,]]]
arr_3 = np.array([1, 2, 3, [2, 5, 1, 6], 51, 27, 16])

arr_3.ndim

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


1

`shape` , `size` metodlari

`shape` metodi massivning qator va ustunlar sonini ko'rsatsa, `size` esa massivlardagi elementlar sonini nomoyon etadi

In [54]:
arr3.shape # arr3 ning qator va o'lchamlarini ko'rsatadi

(2, 4)

In [55]:
arr3.size # arr3 ning elementlar soni

8

N-o'lchamli massivlarni yaratishning boshqa usullari

`zero` va `ones` metodlari yordamida massivlar yaratish

In [35]:
arr4 = np.zeros((2, 4)) # barcha elementlari 0 ga teng (2 qator, 4 element)
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
arr5 = np.ones((2, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`arange` funksiyasi yordamida massiv yaratish

In [38]:
arr6 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
arr7 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
import random

`rand` metodi 0 ~ 1 oralig'idagi taxminiy sonni tanlab oladi 

In [78]:
arr8 = np.random.rand(3, 4)
arr8

array([[0.28435175, 0.02212355, 0.53132347, 0.31623812],
       [0.24235383, 0.28977545, 0.66460464, 0.40796355],
       [0.87386167, 0.47778768, 0.73211455, 0.05352691]])

In [80]:
arr8 = np.random.randint(10, size=(3, 5))
arr8

array([[2, 4, 1, 2, 3],
       [1, 9, 7, 2, 3],
       [7, 2, 5, 9, 0]])