<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/_2_data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Malumot turlari

In [1]:
import numpy as np

- ma'lumot yaratishda ma'lumot turlarini aniq kiritish, 

- ma'lumot turlarini aniqlash, 

- bir turdagi ma'lumot turidan ikkinchi turdagi ma'lumot turiga o'girish


In [2]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [3]:
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3], dtype=int32)

`dype` metodi

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

Bir turdagi ma'lumot turidan boshqasiga o'tkazish

In [9]:
arr = np.array([1, 2, 3, 4]) # int64
arr.dtype

dtype('int64')

`stype` metodi

In [10]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [12]:
float_arr

array([1., 2., 3., 4.])

In [16]:
floats = np.array([1.5, 2.7, 5.9, 4.6])
floats

array([1.5, 2.7, 5.9, 4.6])

**! ! ! `float64` dan `int64` ga o'girganda yo'qotishlar yuz beradi, ya'ni sonning faqat butun qismini olib qoladi**

In [19]:
ints = floats.astype(np.int64)
ints

array([1, 2, 5, 4])