<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/%23_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import numpy as np
import random

Boolean index'lash

- N-o'lchamli massivlar (array)ga ishlov berish 

In [103]:
# Ismlar
names = np.array(['Ilhom', 'Sanjar', 'Sardor', 'Javoxir', 'Sanjar', 'Bobur', 'Ilhom'])
names

array(['Ilhom', 'Sanjar', 'Sardor', 'Javoxir', 'Sanjar', 'Bobur', 'Ilhom'],
      dtype='<U7')

In [104]:
# data (ushbu dataning har bir qatori mos ravishda names massiviga tegishli deb olamiz)
data = np.random.randn(7, 4)
data

array([[ 0.29946638, -0.61508398,  0.82702355,  0.52906046],
       [ 1.39517785, -0.16409609, -0.12822944, -1.62181584],
       [-1.18837096, -1.74420211,  0.20325725,  0.53792712],
       [ 1.09650765, -0.28132951, -1.09859781, -0.82956667],
       [ 0.16661017, -1.80228825,  0.72827563, -0.9072447 ],
       [ 2.47301609,  1.31807481, -1.71451471,  0.77998421],
       [-0.03666292,  1.09587661,  0.48668173,  0.50572711]])

In [105]:
names == 'Sardor'

array([False, False,  True, False, False, False, False])

In [106]:
data[names == 'Sanjar'] # Sanjarga tegishli barcha qatorni ajratib olish

array([[ 1.39517785, -0.16409609, -0.12822944, -1.62181584],
       [ 0.16661017, -1.80228825,  0.72827563, -0.9072447 ]])

In [107]:
data[names == 'Bobur'] # Boburga tegishli barcha qatorni ajratib olish

array([[ 2.47301609,  1.31807481, -1.71451471,  0.77998421]])

In [108]:
data[names == 'Sanjar'] # Sanjarga tegishli barcha qatorni ajratib olish

array([[ 1.39517785, -0.16409609, -0.12822944, -1.62181584],
       [ 0.16661017, -1.80228825,  0.72827563, -0.9072447 ]])

In [109]:
data[names == 'Sanjar', 2:] # Sanjarga tegishli ma'lumotning oxirgi 2 ustunini ajratib olish

array([[-0.12822944, -1.62181584],
       [ 0.72827563, -0.9072447 ]])

In [110]:
data[names != 'Sanjar'] # Sanjarga tegishli bo'lmagan barcha ma'lumotlarni ajratib olish

array([[ 0.29946638, -0.61508398,  0.82702355,  0.52906046],
       [-1.18837096, -1.74420211,  0.20325725,  0.53792712],
       [ 1.09650765, -0.28132951, -1.09859781, -0.82956667],
       [ 2.47301609,  1.31807481, -1.71451471,  0.77998421],
       [-0.03666292,  1.09587661,  0.48668173,  0.50572711]])

In [111]:
data[~(names == 'Sanjar')] # Yuqoridagi natijani ushbu ushul bilan ham amalga oshirish mumkin

array([[ 0.29946638, -0.61508398,  0.82702355,  0.52906046],
       [-1.18837096, -1.74420211,  0.20325725,  0.53792712],
       [ 1.09650765, -0.28132951, -1.09859781, -0.82956667],
       [ 2.47301609,  1.31807481, -1.71451471,  0.77998421],
       [-0.03666292,  1.09587661,  0.48668173,  0.50572711]])

In [112]:
print(names)
print(data)

['Ilhom' 'Sanjar' 'Sardor' 'Javoxir' 'Sanjar' 'Bobur' 'Ilhom']
[[ 0.29946638 -0.61508398  0.82702355  0.52906046]
 [ 1.39517785 -0.16409609 -0.12822944 -1.62181584]
 [-1.18837096 -1.74420211  0.20325725  0.53792712]
 [ 1.09650765 -0.28132951 -1.09859781 -0.82956667]
 [ 0.16661017 -1.80228825  0.72827563 -0.9072447 ]
 [ 2.47301609  1.31807481 -1.71451471  0.77998421]
 [-0.03666292  1.09587661  0.48668173  0.50572711]]


In [113]:
mask = (names == 'Javoxir') | (names == 'Bobur') # Javoxir va Boburga tegishli ma'lumotlarni yagona usul bilan ajratib olish
mask

array([False, False, False,  True, False,  True, False])

In [114]:
data[mask]

array([[ 1.09650765, -0.28132951, -1.09859781, -0.82956667],
       [ 2.47301609,  1.31807481, -1.71451471,  0.77998421]])

In [115]:
data

array([[ 0.29946638, -0.61508398,  0.82702355,  0.52906046],
       [ 1.39517785, -0.16409609, -0.12822944, -1.62181584],
       [-1.18837096, -1.74420211,  0.20325725,  0.53792712],
       [ 1.09650765, -0.28132951, -1.09859781, -0.82956667],
       [ 0.16661017, -1.80228825,  0.72827563, -0.9072447 ],
       [ 2.47301609,  1.31807481, -1.71451471,  0.77998421],
       [-0.03666292,  1.09587661,  0.48668173,  0.50572711]])

In [116]:
data[data<0] # elementlari noldan kichik bo'lgan ma'lumotlarni ajratib olish

array([-0.61508398, -0.16409609, -0.12822944, -1.62181584, -1.18837096,
       -1.74420211, -0.28132951, -1.09859781, -0.82956667, -1.80228825,
       -0.9072447 , -1.71451471, -0.03666292])

In [117]:
data[data<0] = 0 # Yuqoridagi ma'lumotlarni 0 ga tenglash
data

array([[0.29946638, 0.        , 0.82702355, 0.52906046],
       [1.39517785, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.20325725, 0.53792712],
       [1.09650765, 0.        , 0.        , 0.        ],
       [0.16661017, 0.        , 0.72827563, 0.        ],
       [2.47301609, 1.31807481, 0.        , 0.77998421],
       [0.        , 1.09587661, 0.48668173, 0.50572711]])