<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/%23_6_Arr_Or_Pr_1_logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mantiqiy shart operatorlarini massiv operator sifatida qo'llash

In [2]:
import numpy as np

Shart operatori sifatida `where`dan foydalanish

`x_arr` va `y_arr` massiv ma'lumotlariga `True`ni qanoatlantirsa `x_arr` elementini qabul qilgan, aksincha esa `y_arr` elementini qabul qilgan yangi massiv hosil qilinsin

In [3]:
x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [4]:
cond = np.array([True, False, True, True, False])

In [5]:
result = np.where(cond, x_arr, y_arr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
arr1 = np.random.randn(4, 4) # (4, 4) taxminiy massiv
arr1

array([[ 2.41717984, -1.82160165,  1.06176989, -0.36131603],
       [ 0.70686904, -0.7282727 , -1.05602484,  0.36741653],
       [-0.15518173,  0.07653328,  1.78468086, -2.49819288],
       [ 1.03566737, -0.64870937,  1.13607391, -1.50927813]])

In [8]:
result1 = np.where(arr1<0, -2, 2)
result1

array([[ 2, -2,  2, -2],
       [ 2, -2, -2,  2],
       [-2,  2,  2, -2],
       [ 2, -2,  2, -2]])