<a href="https://colab.research.google.com/github/Az1mxoja/Colab/blob/main/%23_8_Arr_Or_Pr_2_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arifmetik amallar

Ko'paytirish, bo'lish, qo'shish, ayirish va h.k amallar

In [2]:
import numpy as np

In [4]:
# data
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

In [5]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

Ko'paytirish

In [8]:
arr1 * arr2 # arr1 elementlarini arr2 mos elementlariga ko'paytirish

array([[ 0,  7, 16],
       [27, 40, 55]])

Bo'lish

In [11]:
arr2 / arr1 # arr2 elementlarini arr1 mos elementlariga bo'lish (bunda bo'linuvchi 0 bo'lsa `infinite` qaytaradi)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

Qo'shish

In [12]:
arr1 + arr2 # arr1 elementlarini arr2 mos elementlariga qo'shish

array([[ 6,  8, 10],
       [12, 14, 16]])

Ayirish

In [13]:
arr2 - arr1 # arr2 elementlaridan arr1 mos elementlarini ayirish

array([[6, 6, 6],
       [6, 6, 6]])

Kvadratga oshirish

In [14]:
arr1 ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [15]:
arr2 * 3

array([[18, 21, 24],
       [27, 30, 33]])

Kvadrat ildizini chiqarish

In [16]:
arr2 ** 0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [17]:
arr1 ** 0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])